version: 3

analyze:
  cli:
    allowlist:
      - "MIT"
      - "Apache-2.0"
      - "BSD-2-Clause"
      - "BSD-3-Clause"
      - "ISC"
      - "CC0-1.0"
      - "Unlicense"
      - "Zlib"
      - "WTFPL"
      - "MPL-2.0"
      - "LGPL-2.1"
      - "LGPL-3.0"
      - "GPL-2.0"
      - "GPL-3.0"

test:
  cli:
    allowlist:
      - "MIT"
      - "Apache-2.0"
      - "BSD-2-Clause"
      - "BSD-3-Clause"
      - "ISC"
      - "CC0-1.0"
      - "Unlicense"
      - "Zlib"
      - "WTFPL"
      - "MPL-2.0"
      - "LGPL-2.1"
      - "LGPL-3.0"
      - "GPL-2.0"
      - "GPL-3.0"

report:
  cli:
    allowlist:
      - "MIT"
      - "Apache-2.0"
      - "BSD-2-Clause"
      - "BSD-3-Clause"
      - "ISC"
      - "CC0-1.0"
      - "Unlicense"
      - "Zlib"
      - "WTFPL"
      - "MPL-2.0"
      - "LGPL-2.1"
      - "LGPL-3.0"
      - "GPL-2.0"
      - "GPL-3.0" 