{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "lean-farm.fullname" . }}
  labels:
    {{- include "lean-farm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "lean-farm.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- range .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  egress:
  {{- range .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }} 