global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerting_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spec-to-Proof API
  - job_name: 'spec-to-proof-api'
    static_configs:
      - targets: ['spec-to-proof-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Lean Farm
  - job_name: 'lean-farm'
    static_configs:
      - targets: ['lean-farm:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Proof Service
  - job_name: 'proof-service'
    static_configs:
      - targets: ['proof-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Drift Processor
  - job_name: 'drift-processor'
    static_configs:
      - targets: ['drift-processor:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Blackbox Exporter (Synthetic Monitoring)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.spec-to-proof.com/health
        - https://api.spec-to-proof.com/metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Kubernetes
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name 